#!/usr/bin/env python3
"""Render or check the Android local manifest from the inspected source lock.

This edits no checkout and performs no network or device operation. The kernel
workspace uses its own pinned manifest, not Android roomservice dependencies.
"""
from __future__ import annotations
import argparse
from pathlib import Path
import xml.etree.ElementTree as ET
from collect_source_evidence import load_lock

ROOT = Path(__file__).resolve().parents[1]


def render(lock: dict) -> str:
    projects = [p for p in lock["projects"] if p["workspace"] == "android"]
    paths = [p["path"] for p in projects]
    if len(projects) != 7 or len(set(paths)) != 7:
        raise ValueError("Expected seven distinct Android checkout paths")
    root = ET.Element("manifest")
    root.append(ET.Comment(" Generated by tools/workspace_manifest.py. Inspected baseline, not boot certification. "))
    ET.SubElement(root, "remote", name="malachite-owned", fetch="https://github.com/")
    for project in projects:
        ET.SubElement(root, "remove-project", path=project["path"], optional="true")
        ET.SubElement(root, "project", name=project["repository"], path=project["path"],
                      remote="malachite-owned", revision=project["revision"],
                      upstream="refs/heads/" + project["branch"])
    ET.indent(root, space="  ")
    return '<?xml version="1.0" encoding="UTF-8"?>\n' + ET.tostring(root, encoding="unicode") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lock", type=Path, default=ROOT / "bringup/source-lock.json")
    parser.add_argument("--output", type=Path, default=ROOT / "bringup/android.xml")
    parser.add_argument("--write", action="store_true", help="Explicitly regenerate the text manifest")
    args = parser.parse_args()
    expected = render(load_lock(args.lock))
    if args.write:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(expected, encoding="utf-8")
        print(f"Wrote {args.output}")
        return 0
    if not args.output.is_file() or args.output.read_text(encoding="utf-8") != expected:
        print("FAIL: Android manifest differs from the source lock; review and regenerate explicitly")
        return 1
    print("PASS: seven Android projects match the twelve-project source lock")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
